#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# SPDX-FileCopyrightText: 2025 René Moll
# SPDX-License-Identifier: MPL-2.0
#

option(BENCHMARK "Enable benchmarks" Off)

if (BENCHMARK)
    find_package(benchmark REQUIRED)

    add_subdirectory(queue_spsc)
endif()
