#
# SPDX-FileCopyrightText: 2025 René Moll
# SPDX-License-Identifier: CC0-1.0
#

version = 1

[[annotations]]
path = [
    ".cppcheck_suppressions",
    ".devcontainer/*",
    ".gitattributes",
    ".gitignore",
    ".pre-commit-config.yaml",
    ".vscode/*",
    "cmake/bob-cmake/*.md",
    "doc/*",
    "README.md",
    "CMakePresets.json"
]
SPDX-FileCopyrightText = "2025 René Moll"
SPDX-License-Identifier = "CC0-1.0"
