#
# SPDX-FileCopyrightText: 2025 René Moll
# SPDX-License-Identifier: CC0-1.0
#

name: CI

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '25 1 * * SUN' # every Sunday at 01:25

jobs:
  build-linux-gcc:
    strategy:
      fail-fast: false
      matrix:
        gcc: [13, 14, 15, 16]
        cxx: [20, 23, 26]
        exclude:
          - gcc: 13
            cxx: 26 # C++26 is not supported by GCC 13

    runs-on: ubuntu-26.04
  
    env:
      CC: gcc-${{ matrix.gcc }}
      CXX: g++-${{ matrix.gcc }}

    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          submodules: 'recursive'

      - name: bootstrap
        run: |
          sudo apt-get update
          sudo apt-get install clang-tidy cmake ninja-build g++-${{ matrix.gcc }} cppcheck flawfinder catch2 iwyu

      - name: Debug build & test
        run: |
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_STANDARD=${{ matrix.cxx }} -B build/ninja-debug -S .
          cmake --build build/ninja-debug/
          ctest --test-dir build/ninja-debug/

      - name: Release build & test
        run: |
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=${{ matrix.cxx }} -B build/ninja-release -S .
          cmake --build build/ninja-release
          ctest --test-dir build/ninja-release/

      - uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: test-logs-gcc-${{ matrix.gcc }}-cxx${{ matrix.cxx }}
          path: build/ninja-*/Testing/Temporary/LastTest.log
          retention-days: 1

  build-linux-clang:
    strategy:
      fail-fast: false
      matrix:
        clang: [20, 21, 22, 23]
        cxx: [20, 23, 26]

    runs-on: ubuntu-26.04

    env:
      CC: clang-${{ matrix.clang }}
      CXX: clang++-${{ matrix.clang }}

    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          submodules: 'recursive'

      - name: bootstrap
        run: |
          sudo apt-get update
          sudo apt-get install clang-tidy cmake ninja-build clang-${{ matrix.clang }} cppcheck flawfinder catch2 iwyu

      - name: Debug build & test
        run: |
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_STANDARD=${{ matrix.cxx }} -B build/ninja-debug -S .
          cmake --build build/ninja-debug/
          ctest --test-dir build/ninja-debug/

      - name: Release build & test
        run: |
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=${{ matrix.cxx }} -B build/ninja-release -S .
          cmake --build build/ninja-release
          ctest --test-dir build/ninja-release/

      - uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: test-logs-clang-${{ matrix.clang }}-cxx${{ matrix.cxx }}
          path: build/ninja-*/Testing/Temporary/LastTest.log
          retention-days: 1

  build-linux-arm-gcc:
    strategy:
      fail-fast: false
      matrix:
        armgcc: ['13.3.Rel1', '14.3.Rel1', '15.3.Rel1']
        cxx: [20, 23]

    runs-on: ubuntu-26.04

    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          submodules: 'recursive'

      - name: bootstrap
        run: |
          sudo apt-get update
          sudo apt-get install clang-tidy cmake ninja-build cppcheck flawfinder iwyu

      - name: ARM GCC bootstrap
        uses: carlosperate/arm-none-eabi-gcc-action@v1.13.0
        with:
          release: '${{ matrix.armgcc }}'

      - name: ARM Cortex-M7 build
        run: |
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_STANDARD=${{ matrix.cxx }} -DCMAKE_TOOLCHAIN_FILE=cmake/bob-cmake/toolchains/toolchain_cortex-m7_fpu_dp.cmake -B build/ninja-m7-debug -S .
          cmake --build build/ninja-m7-debug
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=${{ matrix.cxx }} -DCMAKE_TOOLCHAIN_FILE=cmake/bob-cmake/toolchains/toolchain_cortex-m7_fpu_dp.cmake -B build/ninja-m7-release -S .
          cmake --build build/ninja-m7-release
